| Name                                  | Value       |
| ------------------------------------- | ----------- |
| N8N_BASIC_AUTH_ACTIVE                 | true        |
| N8N_BASIC_AUTH_USER                   | Hack        |
| N8N_BASIC_AUTH_PASSWORD               | admin       |
| N8N_SECURE_COOKIE                     | false       |
| GENERIC_TIMEZONE                      | Europe/Rome |
| DB_SQLITE_POOL_SIZE                   | 1           |
| N8N_RUNNERS_ENABLED                   | true        |
| N8N_BLOCK_ENV_ACCESS_IN_NODE          | false       |
| N8N_GIT_NODE_DISABLE_BARE_REPOS       | true        |
| N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS | true        |
